[[media_extension]]
== Media Extension (Normative)

=== Extension Title

Media

=== Introduction

This extension provides a mechanism for storing multimedia content with features or attributes in a GeoPackage. Examples where this could be used include the following:

* Photographs
* Audio or Video files
  *	PDFs

=== Extension Author

GeoPackage SWG, author_name `gpkg_draft`.

=== Extension Name or Template

`gpkg_draft_media`

=== Extension Type

New requirement dependent on http://www.geopackage.org/spec/#features[Clause 2.1] or http://www.geopackage.org/spec/#features[Clause 2.4].

=== Applicability

This extension applies to feature and attribute tables that are used to hold other media types.

=== Scope

read-write

=== Requirements (Normative)

==== Table Definitions
[[gpkg_ext_relations]]
===== Relations
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL contain a `gpkg_ext_relations` table or view as per <<gpkg_ext_relations_table>> and <<gpkg_ext_relations_sql>>.
====

[[gpkg_ext_relations_table]]
.Extended Relations Table Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id`|INTEGER|Autoincrement primary key|no||PK
|`primary_table_name`|TEXT|Name of the table containing the features or attributes|no||
|`primary_column`|TEXT|Name of the column in `primary_table_name` containing references to media|no||
|`foreign_table_name`|TEXT|Name of the table containing the features or attributes|no||
|`fk_column`|TEXT|Name of the primary key column in `foreign_table_name` used as the foreign key to join with `primary_table_name`|no||
|`relation_name`|TEXT|Name of the relation ('media' for this extension)|no||
|=======================================================================

===== User Defined Media
[[r2]]
[caption=""]
.Requirement 2
====
A GeoPackage that complies with this extension SHALL contain one or more user-defined media tables or views as per <<gpkg_user_defined_media_table>>. These tables MAY contain other columns.
====

[[gpkg_user_defined_media_table]]
.User Defined Media Table Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`id`|INTEGER	|Autoincrement primary key|no|PK
|`data`|BLOB	|Multimedia content|yes|
|`content_type`|TEXT	|mime_type of data|yes|
|=======================================================================

==== Table Values
===== `gpkg_extensions`
[[r3]]
[caption=""]
.Requirement 3
====
A GeoPackage that complies with this extension SHALL contain rows in the `gpkg_extensions` table as described in <<gpkg_extensions_records>>. There SHALL be a row for `gpkg_ext_relations`, one row for each user-defined table containing references to media, and one row for each user-defined media table. For each user-defined table row, there SHALL be a table with the name specified in `table_name` and that table SHALL contain a column with the name specified in `primary_column`.
====

[[gpkg_extensions_records]]
.Extensions Table Record
[cols=",,,,",options="header",]
|=======================================================================
|table_name|column_name|extension_name|definition|scope
|`gpkg_ext_relations`|null|`gpkg_draft_media`|TBD|`read-write`
|_user-defined table name_|_primary column_|`gpkg_draft_media`|TBD|`read-write`
|_user-defined media table name_|null|`gpkg_draft_media`|TBD|`read-write`
|=======================================================================

===== Extended Relations
[[r4]]
[caption=""]
.Requirement 4
====
For each row in `gpkg_extensions` with an `extension_name` of 'gpkg_draft_media' and a non-null `column_name`, there SHALL be a table or view of the name referenced in `table_name` and that table SHALL have a column of the name referenced in `column_name`.
====

[[r5]]
[caption=""]
.Requirement 5
====
For each row in `gpkg_extensions` with an `extension_name` of 'gpkg_draft_media' and non-null `column_name`, there SHALL be a table or view of the name referenced in `table_name` and that table SHALL be a user-defined media table as defined by <<gpkg_user_defined_media_table>>.
====

[[r6]]
[caption=""]
.Requirement 6
====
For user-defined tables as referenced in `gpkg_extensions` and `gpkg_ext_relations`, if the value of its primary column (as specified in <<gpkg_extensions_records>>) is not null, the user-defined media table (specified by `gpkg_ext_relations`) SHALL contain a row with an `id` corresponding to the value in the primary column (also specified by `gpkg_ext_relations`).
====
For example:

* `gpkg_extensions` contains a row with:
** `table_name` of 'features'
** `column_name` of 'media_fk'
* `gpkg_extensions` contains a row with:
** `table_name` of 'media'
** null `column_name`
* `gpkg_ext_relations` contains a row with:
** `primary_table_name` of 'features'
** `primary_column` of `media_fk`
** `foreign_table_name` of 'media'
** `fk_column` of 'id'
** `relation_name` of 'media'

For each row of `features` with a non-null `media_fk`, there must be a row in `media` with a matching `id`.

===== User Defined Media
[[r7]]
[caption=""]
.Requirement 7
====
For a particular row of a user-defined media table, if the value of `data` is not null, the value of `content_type` SHALL NOT be null.
====

=== Table Definition SQL

[[gpkg_ext_relations_sql]]
.Extended Relations Table Definition SQL (Normative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'gpkg_ext_relations' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primary_table_name TEXT NOT NULL,
  primary_column TEXT NOT NULL,
  foreign_table_name TEXT NOT NULL,
  fk_column TEXT NOT NULL,
  relation_name TEXT NOT NULL,
  CONSTRAINT fk_g2dgtct_name FOREIGN KEY('tile_matrix_set_name') REFERENCES gpkg_tile_matrix_set ( table_name ));
----

[[gpkg_extensions_sql]]
.Example User Defined Media Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE sample_media (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data BLOB,
  content_type TEXT;
----

=== Abstract Test Suite (Normative)
TBD

=== References

==== Normative References (Normative)

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document.
For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.
However, parties to agreements based on this part of this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below.
For undated references, the latest edition of the normative document referred to applies.

[bibliography]
- [[[1]]] http://www.geopackage.org/spec[OGC 12-128r10 OGC® GeoPackage Encoding Standard (On-line)]
- [[[1a]]] https://portal.opengeospatial.org/files/?artifact_id=56357[OGC 12-128r10 OGC® GeoPackage Encoding Standard (PDF)]
