[[media_extension]]
== Media Extension (Normative)

=== Extension Title

Media

=== Introduction

This extension provides a mechanism for storing multimedia content with features in a GeoPackage. Examples where this could be used include the following:

* Photographs
* Audio or Video files
*	PDFs

=== Extension Author

GeoPackage SWG, author_name `gpkg_draft`.

=== Extension Name or Template

`gpkg_draft_media`

=== Extension Type

New requirement dependent on http://www.geopackage.org/spec/#features[Clause 2.1] or http://www.geopackage.org/spec/#features[Clause 2.4].

=== Applicability

This extension defines a relationship between feature tables and aspatial tables that hold related media.

=== Scope

read-write

=== Requirements (Normative)

==== Table Definitions
[[gpkgext_relations]]
===== Relations
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL contain a `gpkgext_relations` table or view as per <<gpkgext_relations_table>> and <<gpkgext_relations_sql>>.
====

[[gpkgext_relations_table]]
.Extended Relations Table Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id`|INTEGER|Autoincrement primary key|no||PK
|`primary_table_name`|TEXT|Name of the table containing the features or attributes|no||
|`primary_column`|TEXT|Name of the primary key column in `primary_table_name` |no||
|`foreign_table_name`|TEXT|Name of the table containing the media|no||
|`foreign_column`|TEXT|Name of the foreign key column in `foreign_table_name` used as the foreign key to join with `primary_table_name` on the `primary_column` |no||
|`relation_name`|TEXT|Name of the relation ('media' for this extension)|no||
|=======================================================================

===== User Defined Media
[[r2]]
[caption=""]
.Requirement 2
====
A GeoPackage that complies with this extension SHALL contain one or more user-defined media tables or views as per <<gpkg_user_defined_media_table>>. These tables MAY contain other columns.
====

[[gpkg_user_defined_media_table]]
.User Defined Media Table Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`id`|INTEGER	|Autoincrement primary key|no|PK
|`data`|BLOB	|Multimedia content|no|
|`content_type`|TEXT	|mime_type of data|no|
|_foreign_column_|TEXT	|foreign key as defined in <<gpkgext_relations_table>>|yes|FK
|=======================================================================

==== Table Values
===== `gpkg_extensions`
[[r3]]
[caption=""]
.Requirement 3
====
A GeoPackage that complies with this extension SHALL contain rows in the `gpkg_extensions` table as described in <<gpkg_extensions_records>>. There SHALL be a row for `gpkgext_relations`.
====

[[gpkg_extensions_records]]
.Extensions Table Record
[cols=",,,,",options="header",]
|=======================================================================
|table_name|column_name|extension_name|definition|scope
|`gpkgext_relations`|null|`gpkg_draft_media`|TBD|`read-write`
|=======================================================================

===== Extended Relations
[[r4]]
[caption=""]
.Requirement 4
====
For each row in `gpkgext_relations` there SHALL be a table or view of the name referenced in `primary_table_name` and that table SHALL have an entry in gpkg_contents with a data_type of `features`.
====

[[r5]]
[caption=""]
.Requirement 5
====

For each row in `gpkgext_relations` there SHALL be a table or view of the name referenced in `foreign_table_name` and that table SHALL have an entry in gpkg_contents with a data_type of `aspatial` and that table SHALL be a user-defined media table as defined by <<gpkg_user_defined_media_table>>.

====

[[r6]]
[caption=""]
.Requirement 6
====
For user-defined media tables as referenced in `gpkgext_relations`, if the value of its foreign column (as specified in <<gpkgext_relations_table>>) is not null, the corresponding user-defined primary table (specified by `gpkgext_relations`) SHALL contain a row with an `id` corresponding to the value in that foreign column.
====
For example:

* `gpkgext_relations` contains a row with:
** `primary_table_name` of 'features'
** `primary_column` of `relation_column`
** `foreign_table_name` of 'media'
** `foreign_column` of 'relation_column'
** `relation_name` of 'media'

.features
|=======================================================================
|feature_id|primary_column|
|1|7|
|=======================================================================

.media
|=======================================================================
|id|data|content_type|foreign_column
|17|<BLOB>|image/png|7
|=======================================================================

For each row of media with a non-null foreign_column, there must be a row in features with a matching id in the  primary_column.

=== Table Definition SQL

[[gpkgext_relations_sql]]
.Extended Relations Table Definition SQL (Normative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'gpkgext_relations' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primary_table_name TEXT NOT NULL,
  primary_column TEXT NOT NULL,
  foreign_table_name TEXT NOT NULL,
  foreign_column TEXT NOT NULL,
  relation_name TEXT NOT NULL
 );
----

[[gpkg_extensions_sql]]
.Example User Defined Media Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_media' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data BLOB NOT NULL,
  content_type TEXT NOT NULL,
  _foreign_column_ TEXT NULL);
----

=== Abstract Test Suite (Normative)
TBD

=== References

==== Normative References (Normative)

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document.
For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.
However, parties to agreements based on this part of this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below.
For undated references, the latest edition of the normative document referred to applies.

[bibliography]
- [[[1]]] http://www.geopackage.org/spec[OGC 12-128r10 OGC® GeoPackage Encoding Standard (On-line)]
- [[[1a]]] https://portal.opengeospatial.org/files/?artifact_id=56357[OGC 12-128r10 OGC® GeoPackage Encoding Standard (PDF)]
