[[media_extension]]
== Related Tables Extension (Normative)

=== Extension Title

Related Tables

=== Introduction

The GeoPackage Related Tables extension defines the rules and requirements for associating tables with existing feature or attribute tables in a GeoPackage data store<<1>>. One use case for this extension is to associate features with related multimedia content such as:

* photographs;
* audio or video files; or,
* PDFs.

For example, implementing this extension would provide the ability to associated pictures of a house with a specific parcel.

This extension, like all GeoPackage extensions, is intended to be transparent and to not interfere with GPKG compliant, but non-supporting, software packages. The http://www.opengeospatial.org/projects/initiatives/gpkg-rteie[OGC GeoPackage (GPKG) Related Tables Extension Interoperability Experiment (GPKG-RTE IE)] verified that the extension is correctly designed to meet the design goals and to be transparent in this manner. The goal of the IE was achieved by building GeoPackages containing embedded multimedia content and sharing those GeoPackages with other software products. This IE produced an OGC Engineering Report <<2>> that discusses whether the extension is fit for use and adoption by the OGC.

=== Extension Author

GeoPackage SWG (no author name until adopted by OGC)footnote:[This extension is based on the `compusult_extrelations1` extension developed by http://compusult.net[Compusult].]

=== Extension Name or Template

`related_tables` (If this extension is adopted by OGC, then `gpkg_related_tables` will be named as an alias.)

=== Extension Type

This extension provides new requirements dependent on GeoPackage http://www.geopackage.org/spec120/index.html#features[Clause 2.1] and http://www.geopackage.org/spec120/index.html#attributes[Clause 2.4].

=== Applicability

This extension defines a relationship between feature tables and aspatial tables that hold related media.

=== Scope

read-write

=== Requirements (Normative)

==== Table Definitions
[[gpkgext_relations]]
===== Relations
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL contain a `gpkgext_relations` table or view as per <<gpkgext_relations_table>> and <<gpkgext_relations_sql>>.
====

[[r2]]
[caption=""]
.Requirement 2
====
If a mapping to support many-to-many relationships is required, the `mapping_table` column SHALL contain the name of a table that has two columns named `primary_column_value` and `foreign_column_value` which will contain data values for, and link to, the `primary_column` and `foreign_column` named in the `gpkgext_relations` table. <<r2>> describes this table. For many-to-many cases, this would be the primary key or `id` column.
====

[[r3]]
[caption=""]
.Requirement 3
====
The relation defined in the `gpkgext_relations` table may or may not use the id or primary key columns to link the primary and foreign tables.
====

[[gpkgext_relations_table]]
.Extended Relations Table Definition
[cols="10,5,40,5,5,5,5",options="header",]
|=======================================================================
|Column Name            |Column Type  |Column Description                                                    |Null |Default  |Key |Unique
|`id`                   |INTEGER      |Autoincrement primary key                                             |no   |         |PK  |yes
|`primary_table_name`   |TEXT         |Name of the table containing the features or attributes               |no   |         |    |no
|`primary_column`       |TEXT         |Name of the primary key column in `primary_table_name`                |no   |         |    |no
|`attribute_table_name` |TEXT         |Name of the table containing the attributes                           |no   |         |    |no
|`attribute_column`     |TEXT         |Name of the primary key column in `attribute_table_name`              |no   |         |    |no
|`relation_name`        |TEXT         |Name of the relation ('media' for this extension)                     |no   |         |    |no
|`mapping_table`        |TEXT         |Name of a mapping table used to support many-to-many type mappings    |no   |         |    |yes
|`cardinality`          |TEXT         |One of `one-to-many`, `many-to-one`, or `many-to-many`                |no   |         |    |yes
|=======================================================================

===== User Defined Mapping Tables
[[r4]]
[caption=""]
.Requirement 4
====
A GeoPackage that complies with this extension SHALL contain a mapping table for each distinct value in the `mapping_table` column of the `gpkgext_relations_table` as per  <<gpkgext_user_defined_mapping_table>>.

[[r5]]
[caption=""]
.Requirement 5
====
A mapping table MAY contain no rows. Each row that is present SHALL map a row of a feature/attribute/tile table to a row of the attribute table. The two columns SHALL be used to map between the core data table using the `primary_column_id` and the attribute table using the `attribute_column_id`.

[[r6]]
[caption=""]
.Requirement 6
====
The two columns of a mapping table SHALL be used to map between the core data table using the `primary_column_id` and the attribute table using the `attribute_column_id`.
====
[[gpkgext_user_defined_mapping_table]]
.User Defined Mapping Table Definition
[cols=",,,,,,",options="header",]

|=================================================================
|Column Name           | Column Type | Column Description                                     |Null |Default  |Key |Unique
|`primary_column_id`   | INTEGER     | Name of the primary key column in the primary table    |no   |         |    |no
|`attribute_column_id` | INTEGER     | Name of the primary key column in the attribute table  |no   |         |    |no
|=================================================================

===== User Defined Attributes (Media) Tables
[[r7]]
[caption=""]
.Requirement 7
====
A GeoPackage that complies with this extension SHALL contain one or more user-defined attribute (media) tables or views as per <<gpkg_user_defined_media_table>>. These tables MAY contain other columns.
====

[[gpkg_user_defined_media_table]]
.User Defined Media Table Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name    |Column Type |Column Description        |Null |Key
|`id`           |INTEGER     |Autoincrement primary key |no   |PK
|`data`         |BLOB        |Multimedia content        |no   |
|`content_type` |TEXT        |Mime-type of data         |no   |
|=======================================================================

==== Table Values
===== `gpkg_extensions`
[[r8]]
[caption=""]
.Requirement 8
====
A GeoPackage that complies with the Related Tables extension SHALL contain rows in the `gpkg_extensions` table as described in <<gpkg_extensions_records>>. There SHALL be a row for `gpkgext_relations`.
====

[[gpkg_extensions_records]]
.Extensions Table Record
[cols=",,,,",options="header",]
|=======================================================================
|table_name|column_name|extension_name|definition|scope
|`gpkgext_relations`|null|`related_tables`|TBD|`read-write`
|_name of actual <<gpkgext_user_defined_mapping_table,extended relations mapping table>>_|null|`related_tables`|TBD|`read-write`
|=======================================================================

===== Extended Relations
[[r9]]
[caption=""]
.Requirement 9
====
For each row in `gpkgext_relations`, there SHALL be a table or view of the name referenced in `primary_table_name` and that table SHALL have an entry in `gpkg_contents`.
====

[[r10]]
[caption=""]
.Requirement 10
====
For each row in `gpkgext_relations`, there SHALL be a table or view of the name specified in `attribute_table_name`. This attributes table SHALL have an entry in `gpkg_contents` with a `data_type` of 'attributes'. The attribute table SHALL be a user-defined media table as defined by <<gpkg_user_defined_media_table>>.
====

[NOTE]
====
The `cardinality` column is informational only. It should be populated during the data load process and updated by the GeoPackage client if needed. Export processes may use this column to determine the right way to export the data.
====

====== Example

This example illustrates support for many-to-many relationships but the concept may be used in a degenerative way to support one-to-many or many-to-one relationships.
The content of the `gpkgext_relations` includes a <<features_to_media>> that relates the <<features>> and <<media>> using their respective `id` columns.

In this example, there are four features (ID 1, 2, 3 and 4) and three PNG media items (ID 17, 18, and 19).
Using the <<features_to_media>>,

 * feature 1 relates to media 17 and 18
 * feature 2 relates to media 18
 * feature 3 relates to media 18
 * feature 4 relates to media 17 and 19

.gpkgext_relations table values
[options="header"]
|==============================================
|primary_table_name|primary_column|attribute_table_name|attribute_column|relation_name|mapping_table|cardinality
|features          |id            |media               |id              |media        |features_to_media|many-to-many
|==============================================

[[features]]
.features table values
[width="50%",options="header"]
|=======================================================================
|id|geom
|1|<BLOB>
|2|<BLOB>
|3|<BLOB>
|4|<BLOB>
|=======================================================================

[[media]]
.media table values
[width="80%",options="header"]
|=======================================================================
|id|data|content_type
|17|<BLOB>|image/png
|18|<BLOB>|image/png
|19|<BLOB>|image/png
|=======================================================================

[[features_to_media]]
.features_to_media table
[options="header"]
|==============================================
|primary_column_value|attribute_column_value
|4  | 17
|4  | 19
|3  | 18
|2  | 18
|1  | 18
|1  | 17
|==============================================

The <<features_to_media>> relates the id columns between the features table and the media table.


=== Table Definition SQL

[[gpkgext_relations_sql]]
.Extended Relations Table Definition SQL (Normative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'gpkgext_relations' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primary_table_name TEXT NOT NULL,
  primary_column TEXT NOT NULL,
  foreign_table_name TEXT NOT NULL,
  foreign_column TEXT NOT NULL,
  relation_name TEXT NOT NULL,
  mapping_table TEXT UNIQUE,
  cardinality TEXT NOT NULL
 );
----

[[gpkgext_user_defined_mapping_table_sql]]
.Extended Relations Mapping Table SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_mapping_table' (
  primary_column_id INTEGER NOT NULL,
  attribute_column_id INTEGER NOT NULL
 );
----

[[gpkg_features_sql]]
.Example User Defined Features Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_feature_table' (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  geometry GEOMETRY,
  text_attribute TEXT,
  real_attribute REAL,
  boolean_attribute BOOLEAN,
  relation TEXT NULL);
----
This table is a modified version of http://www.geopackage.org/spec/#_sample_feature_table_informative[the informative example in the core document].

[[gpkg_extensions_sql]]
.Example User Defined Media Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_media' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data BLOB NOT NULL,
  content_type TEXT NOT NULL,
  relation TEXT NULL);
----

=== Abstract Test Suite (Normative)
TBD

=== References

==== Normative References

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document.
For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.
However, parties to agreements based on this part of this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below.
For undated references, the latest edition of the normative document referenced applies.

[bibliography]
- [[[1]]] http://www.geopackage.org/spec120/index.html[OGC 12-128r14 OGC® GeoPackage Encoding Standard v1.2.0 (On-line)]
- [[[2]]] TBD
