[[media_extension]]
== Related Tables Extension (Normative)

=== Extension Title

Related Tables

=== Introduction

This extension provides a mechanism for associating tables with existing feature or attribute tables in a GeoPackage. One use case for this extension is to associate features with multimedia content such as:

* Photographs
* Audio or Video files
* PDFs

This extension is based on the `compusult_extrelations1` extension developed by http://compusult.net[Compusult].

This extension is the subject of the OGC GeoPackage (GPKG) Related Tables Extension Interoperability Experiment (GPKG-RTE IE).

=== Extension Author

GeoPackage SWG (no author name until adopted by OGC)

=== Extension Name or Template

`related_tables` (If this extension is adopted by OGC, then `gpkg_related_tables` will be named as an alias.)

=== Extension Type

New requirement dependent on http://www.geopackage.org/spec/#features[Clause 2.1] and http://www.geopackage.org/spec/#attributes[Clause 2.4].

=== Applicability

This extension defines a relationship between feature tables and aspatial tables that hold related media.

=== Scope

read-write

=== Requirements (Normative)

==== Table Definitions
[[gpkgext_relations]]
===== Relations
[[r1]]
[caption=""]
.Requirement 1
====
A GeoPackage that complies with this extension SHALL contain a `gpkgext_relations` table or view as per <<gpkgext_relations_table>> and <<gpkgext_relations_sql>>.

If a mapping to support many to many relationships is required, the `mapping_table` column SHALL contain the name of a table that has two columns called `primary_column_value` and `foreign_column_value` which will contain data values for, and link to, the `primary_column` and `foreign_column` named in the `gpkgext_relations` table. <<r2>> describes this table. For many-to-many cases, this would be the primary key or `id` column.

The relation defined in the `gpkgext_relations` table may or may not use the id or primary key columns to link the primary and foreign tables.
====

[[gpkgext_relations_table]]
.Extended Relations Table Definition
[cols=",,,,,,",options="header",]
|=======================================================================
|Column Name          |Column Type  |Column Description                                                                                                                       |Null |Default  |Key |Unique
|`id`                 |INTEGER      |Autoincrement primary key                                                                                                                |no   |         |PK    |yes
|`primary_table_name` |TEXT         |Name of the table containing the features or attributes                                                                                  |no   |         |      |no
|`primary_column`     |TEXT         |Name of the primary key column in `primary_table_name`                                                                                   |no   |         |      |no
|`foreign_table_name` |TEXT         |Name of the table containing the media                                                                                                   |no   |         |      |no
|`foreign_column`     |TEXT         |Name of the foreign key column in `foreign_table_name` used as the foreign key to join with `primary_table_name` on the `primary_column` |no   |         |      |no
|`relation_name`      |TEXT         |Name of the relation ('media' for this extension)                                                                                        |no   |         |      |no
|`mapping_table`      |TEXT         |Name of a mapping table used to support many-to-many etc. type mappings                                                                  |yes  |         |      |yes
|=======================================================================

===== Mapping Tables
[[r2]]
[caption=""]
.Requirement 2
====
A GeoPackage that complies to this extension SHALL contain a mapping table for each non-null value in the `mapping_table` column of the `gpkgext_relations_table`. Any such mapping table must take its name from that value. Any such mapping table SHALL define values for mapping row(s) of a feature/attribute/tile table to row(s) of the media table. Two columns SHALL be used to map between the core data table(`primary_column`) and the media table (`foreign_column`). The two columns SHALL be named `primary_column_value` and `foreign_column_value` and SHALL have the respective data types and sizes of the corresponding columns from their respective data tables.

====
[[gpkgext_user_defined_mapping_table]]
.Extended Relations Mapping Table Definition
[cols=",,,,,,",options="header",]

|=================================================================
|Column Name | Column Type | Column Description  |Null |Default  |Key |Unique
|`primary_column_value`     |determined by the data type of the `primary_column` matched to this mapping table name in _gpkgext_relations_table_  |Name of the primary key column in `primary_table_name` |no   |         |      |no
|`foreign_column_value`     |determined by the data type of the `foreign_column` matched to this mapping table name in _gpkgext_relations_table_  |Name of the foreign key column in `foreign_table_name` used as the foreign key to join with `primary_table_name` on the `primary_column` |no   |         |      |no
|=================================================================


===== User Defined Media
[[r3]]
[caption=""]
.Requirement 3
====
A GeoPackage that complies with this extension SHALL contain one or more user-defined media tables or views as per <<gpkg_user_defined_media_table>>. These tables MAY contain other columns.
====

[[gpkg_user_defined_media_table]]
.User Defined Media Table Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`id`|INTEGER	|Autoincrement primary key|no|PK
|`data`|BLOB	|Multimedia content|no|
|`content_type`|TEXT	|mime_type of data|no|
|_foreign_column_|TEXT	|foreign key as defined in <<gpkgext_relations_table>>|yes|FK
|=======================================================================

==== Table Values
===== `gpkg_extensions`
[[r4]]
[caption=""]
.Requirement 4
====
A GeoPackage that complies with this extension SHALL contain rows in the `gpkg_extensions` table as described in <<gpkg_extensions_records>>. There SHALL be a row for `gpkgext_relations`.
====

[[gpkg_extensions_records]]
.Extensions Table Record
[cols=",,,,",options="header",]
|=======================================================================
|table_name|column_name|extension_name|definition|scope
|`gpkgext_relations`|null|`related_tables`|TBD|`read-write`
|=======================================================================

===== Extended Relations
[[r5]]
[caption=""]
.Requirement 5
====
For each row in `gpkgext_relations` there SHALL be a table or view of the name referenced in `primary_table_name` and that table SHALL have an entry in `gpkg_contents`.
====

[[r6]]
[caption=""]
.Requirement 6
====

For each row in `gpkgext_relations` there SHALL be a table or view of the name referenced in `foreign_table_name` and that table SHALL have an entry in `gpkg_contents` with a `data_type` of 'attributes' and that table SHALL be a user-defined media table as defined by <<gpkg_user_defined_media_table>>.

====

[[r7]]
[caption=""]
.Requirement 7
====
For each row in `gpkgext_relations` there SHALL be a table or view of the name referenced in `foreign_table_name` and that table SHALL have an entry in `gpkg_contents` with a `data_type` of 'attributes' and that table SHALL be a user-defined media table as defined by <<gpkg_user_defined_media_table>>.

====

[[r8]]
[caption=""]
.Requirement 8
====
For any user-defined media table, as referenced in `gpkgext_relations`, if the value of its `foreign_column` (as specified in <<gpkgext_relations_table>>) is not null, the corresponding user-defined primary table (specified by `gpkgext_relations`) SHALL contain at least one row with a value in its `primary_column` (specified by `gpkgext_relations`) equal to the value in the user-defined media table `foreign_column`.
====
The values in `primary_column` and `foreign_column` SHOULD uniquely identify the relationship. There are a number of valid ways to do this including sequences and UUIDs.

====== Example
In this example, there are three features (ID 1, 2, and 3) and three media values (ID 17, 18, and 19). Media ID 17 links to Features with ID 1 and 2 (relation 7). Feature ID 3 links to both media ID 18 and 19 (relation 8).

.gpkgext_relations table values
[options="header"]
|==============================================
|primary_table_name|primary_column|foreign_table_name|foreign_column|relation_name|mapping_table
|features|relation|media|relation|media|null
|==============================================

.features table values
[width="50%",options="header"]
|=======================================================================
|id|relation
|1|7
|2|7
|3|8
|4|8
|=======================================================================

.media table values
[width="80%",options="header"]
|=======================================================================
|id|data|content_type|relation
|17|<BLOB>|image/png|7
|18|<BLOB>|image/png|8
|19|<BLOB>|image/png|8
|=======================================================================

For each row of media with a non-null `relation`, there must be at least one row in `features` with a matching id in the `relation`.

This allows for one-to-many, and many-to-one relationships between features and related media.

To support many-to-many relationships, the content of the `gpkgext_relations` would change to name a mapping table used to map between the core data table and its related table.

.gpkgext_relations table values
[options="header"]
|==============================================
|primary_table_name|primary_column|foreign_table_name|foreign_column|relation_name|mapping_table
|features|id|media|id|media|features_to_media
|==============================================

The example mapping table called `features_to_media` relates on ids. In the example below, the relations map the id columns from the features table and the media table.

.example features_to_media table values
[options="header"]
|==============================================
|primary_column_value|foreign_column_value
|4  | 17
|4  | 19
|3  | 18
|2  | 18
|1  | 18
|1  | 17
|==============================================


=== Table Definition SQL

[[gpkgext_relations_sql]]
.Extended Relations Table Definition SQL (Normative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'gpkgext_relations' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primary_table_name TEXT NOT NULL,
  primary_column TEXT NOT NULL,
  foreign_table_name TEXT NOT NULL,
  foreign_column TEXT NOT NULL,
  relation_name TEXT NOT NULL
 );
----

[[gpkgext_user_defined_mapping_table_sql]]
.Extended Relations Mapping Table SQL (Normative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_mapping_table' (
  primary_column_value TEXT NOT NULL,
  foreign_column_value TEXT NOT NULL
 );
----

[[gpkg_features_sql]]
.Example User Defined Features Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_feature_table' (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  geometry GEOMETRY,
  text_attribute TEXT,
  real_attribute REAL,
  boolean_attribute BOOLEAN,
  relation TEXT NULL);
----
This table is a modified version of http://www.geopackage.org/spec/#_sample_feature_table_informative[the informative example in the core document].

[[gpkg_extensions_sql]]
.Example User Defined Media Table Definition SQL (Informative)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE 'sample_media' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data BLOB NOT NULL,
  content_type TEXT NOT NULL,
  relation TEXT NULL);
----

=== Abstract Test Suite (Normative)
TBD

=== References

==== Normative References (Normative)

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document.
For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.
However, parties to agreements based on this part of this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below.
For undated references, the latest edition of the normative document referred to applies.

[bibliography]
- [[[1]]] http://www.geopackage.org/spec[OGC 12-128r14 OGC® GeoPackage Encoding Standard (On-line)]
